name: Docker

on:
  push:
    branches:
      - master

jobs:
  publish-bot:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        app: ['bot', 'backend']

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: "apps/${{ matrix.app }}"
        run: docker build . --file Dockerfile --tag ${{ matrix.app }}

      - name: Log into registry
        working-directory: "apps/${{ matrix.app }}"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        working-directory: "apps/${{ matrix.app }}"
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${{ matrix.app }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag ${{ matrix.app }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
